export const translations = {
  en: {
    nav: {
      company: "Company",
      product: "Product",
      dataset: "Dataset",
      support: "Support",
      exploreProduct: "Explore ViC",
      talkToUs: "Talk to us",
      requestDemo: "Request a demo",
      emailSupport: "Email support",
    },
    home: {
      hero: {
        titleLine1: "We turn medical images",
        titleLine2: "into decisions.",
        description:
          "IntusAI designs software for clinical teams. Our flagship product, VirtualClone (ViC), brings AI segmentation and accurate 3D-visualization to everyday surgical planning.",
        discover: "Discover ViC",
        about: "About IntusAI",
      },
      about: {
        title: "About IntusAI",
        paragraph1:
          "We build tools that make imaging clearer and faster. By combining machine learning, clinical collaboration and careful product design, we help teams plan with confidence, communicate better and save time in high-stakes workflows.",
        paragraph2:
          "Our work focuses on abdominal-thoracic surgery, with robust support for liver, pancreas, kidney and lungs planning.",
        list: [
          "AI segmentation and 3D visualization",
          "DICOM/NRRD interoperability",
          "Web-based access, on-prem or cloud",
          "Privacy by design & audit trails",
        ],
      },
      why: {
        title: "Why IntusAI",
        cards: [
          { title: "Clinical focus", body: "Designed with surgeons for planning and pre-operative guidance." },
          { title: "Time to value", body: "Fast inference, clear UI." },
          { title: "Interoperability", body: "Standards-based formats and patient-specific integrations." },
        ],
        cta: "Explore VirtualClone (ViC)",
      },
      contact: {
        badge: "Contact us",
        title: "Want to see ViC in action?",
        description:
          "Our team can guide you through onboarding, integrations, or custom workflows. Reach out from the dedicated support page.",
        cta: "Go to support page",
      },
    },
    dataset: {
      hero: {
        badge: "High-quality surgical imaging dataset",
        title: "Algorithms trained on high-quality medical images.",
        description:
          "IntusAI trains its ViC networks on a proprietary, multicenter dataset with more than 2,600 annotated abdominal and thoracic CT scans. The fidelity of that source data keeps our segmentation, visualization and decision layers dependable in surgical workflows.",
        explore: "Explore dataset",
      },
      stats: {
        title: "Network performance grounded in data",
        description:
          "Our segmentation models rely on high-quality, high-volume imaging. That foundation keeps the ViC stack reliable for AI training, radiomics and clinical validation.",
        metrics: [
          { label: "Dataset - high-quality CT scans", value: "> 2,600 annotated" },
          { label: "Reconstructed structures", value: "10 anatomy classes" },
          { label: "Mean DICE score", value: "0.85 average across ViC reconstructions" },
          { label: "Prediction time", value: "< 5 minutes" },
        ],
        note: "We maintain a continuous improvement loop: new clinical collaborations expand the dataset, while anonymization and bias checks keep it research-ready.",
      },
      ircad: {
        badge: "Dataset",
        title: "Built on trusted academic data sources",
        description:
          "A portion of our training data originates from IRCAD. We share 20 IRCAD cases curated and verified by our team (not generated by ViC) with high-accuracy segmentations you can re-use or compare against your own annotations or guidelines.",
        downloadCta: "Download ViC dataset",
      },
      collab: {
        badge: "Clinical & engineering",
        title: "Collaboration-ready networks",
        description:
          "We work with surgical teams, imaging labs and engineering departments to co-develop AI services, validation studies or bespoke reconstructions. Share your objectives - AI benchmarking, radiomic discovery, multi-center validation - and we tailor access plus expert support.",
        startCta: "Start a collaboration",
      },
    },
    sliceViewer: {
      title: "Example of a ViC segmented case",
      caption:
        "A short stack of slices from a ViC-segmented case - scroll through to see how our networks automatically outline organs and vessels.",
    },
    supportPage: {
      nav: {
        company: "Company",
        product: "Product",
        dataset: "Dataset",
        support: "Support",
        emailSupport: "Email support",
      },
      hero: {
        badge: "Support",
        title: "We are here to help your team succeed with ViC.",
        intro:
          'Choose one of the options below or write to <a href="mailto:info@intusai.com">info@intusai.com</a> for tailored assistance.',
      },
      cards: {
        manual: {
          title: "Request User Manual",
          body: "Get the latest VirtualClone (ViC) user manual.",
          cta: "Request user manual",
        },
        contact: {
          title: "Contact us",
          body:
            "Need help with onboarding, integrations, or clinical validation? Our support engineers and clinical specialists can guide you end-to-end.",
          cta: "Contact us",
        },
      },
      manualForm: {
        badge: "Manual request",
        title: "Request the latest ViC User Manual",
        description: "Fill in the form and we will share the current documentation package within two business days.",
        fields: {
          firstName: "First name",
          lastName: "Last name",
          hospital: "Hospital / Institution",
          department: "Department / Role",
          email: "Work email",
          phone: "Phone (optional)",
          country: "Country",
          useCase: "Primary use case",
          notes: "Additional notes",
        },
        placeholders: {
          firstName: "Maria",
          lastName: "Rossi",
          hospital: "IRCCS San Raffaele",
          department: "Hepatobiliary Surgery",
          email: "name@hospital.org",
          phone: "+39 02 1234567",
          country: "Italy",
          useCase: "Liver transplant planning",
          notes: "Share clinical scenario, preferred onboarding dates, or regulatory needs.",
        },
        consentPrimary:
          'I confirm I have read the <a href="/privacy">privacy policy</a> and agree to be contacted by IntusAI about ViC.',
        consentSecondary: "I would like to receive occasional product updates and clinical validation notes.",
        submit: "Submit request",
        emailHint: 'Prefer email? Write to <a href="mailto:info@intusai.com">info@intusai.com</a>.',
      },
      contactSection: {
        badge: "Contact us",
        title: "Talk directly with IntusAI",
        intro: "We respond within two business days. Tell us how we can help your surgical planning workflow or integration.",
        hqTitle: "Headquarters",
        hqCity: "Milan, Italy",
        hqAddress: "Via San Senatore 6/1\n20122 Milano (MI)",
        phoneTitle: "Direct line",
        phoneValue: "0000 000000",
        phoneHours: "Mon-Fri, 09:00-18:00 CET",
        emailTitle: "Email",
        emailValue: "info@intusai.com",
        form: {
          badge: "Write to us",
          title: "Tell us about your request",
          name: "Full name",
          email: "Work email",
          message: "Message",
          placeholderName: "Dr. Elisa Conti",
          placeholderEmail: "elisa.conti@hospital.org",
          placeholderMessage: "Describe the clinical scenario, timeline, or special requests.",
          privacy:
            'I agree to the <a href="/privacy">privacy policy</a> and to be contacted about my request.',
          submit: "Send message",
        },
      },
    },
  },
  it: {
    nav: {
      company: "Azienda",
      product: "Prodotto",
      dataset: "Dataset",
      support: "Supporto",
      exploreProduct: "Esplora ViC",
      talkToUs: "Contattaci",
      requestDemo: "Richiedi una demo",
      emailSupport: "Scrivi al supporto",
    },
    dataset: {
      hero: {
        badge: "Dataset chirurgico di alta qualita",
        title: "Algoritmi addestrati su immagini di alta qualita.",
        description:
          "IntusAI addestra le reti ViC su un dataset multicentrico con oltre 2.600 TAC addominali e toraciche segmentate. L'alta qualita delle immagini di origine garantisce risultati eccellenti in termini di segmentazione, visualizzazione e supporto decisionale nei flussi chirurgici.",
        explore: "Esplora il dataset",
      },
      stats: {
        title: "Prestazioni delle reti basate sui dati",
        description:
          "I nostri modelli di segmentazione si basano su immagini ad alta qualita e grandi volumi. Questa struttura rende ViC una piattaforma affidabile per AI training, radiomica e validazione clinica",
        metrics: [
          { label: "Dataset - TAC di alta qualita", value: "> 2.600 annotate" },
          { label: "Strutture ricostruite", value: "10 classi anatomiche" },
          { label: "DICE medio", value: "0,85 di media sulle ricostruzioni ViC" },
          { label: "Tempo di predizione", value: "< 5 minuti" },
        ],
        note: "Manteniamo un ciclo di miglioramento continuo; periodicamente nuove collaborazioni cliniche ampliano il dataset.",
      },
      ircad: {
        badge: "Dataset",
        title: "Costruito da fonti affidabili",
        description:
          "Parte dei nostri dati di training proviene da IRCAD. Condividiamo 20 casi IRCAD curati e verificati dal nostro team (non generati da ViC), con segmentazioni ad alta accuratezza da riusare o confrontare con le tue annotazioni e linee guida.",
        downloadCta: "Ottieni dataset",
      },
      collab: {
        badge: "Clinico & ingegneristico",
        title: "Reti pronte alla collaborazione",
        description:
          "Collaboriamo con team chirurgici, imaging lab e reparti ingegneristici per sviluppare servizi AI, studi di validazione o ricostruzioni paziente-specifico. Raccontaci obiettivi - benchmarking AI, radiomica - e adatteremo accesso e supporto specialistico.",
        startCta: "Avvia una collaborazione",
      },
    },
    sliceViewer: {
      title: "Esempio di caso segmentato da ViC",
      caption:
        "Una breve serie di slice provenienti da un caso segmentato automaticamente da ViC: scorri per vedere come le nostre reti segmentano organi, vasi e masse.",
    },
    home: {
      hero: {
        titleLine1: "Trasformiamo le immagini",
        titleLine2: "in decisioni.",
        description:
          "IntusAI sviluppa software avanzati per i team clinici. Il nostro prodotto di punta, VirtualClone (ViC), integra segmentazione AI e visualizzazione 3D nella pianificazione chirurgica quotidiana.",
        discover: "Scopri ViC",
        about: "Su IntusAI",
      },
      about: {
        title: "Su IntusAI",
        paragraph1:
          "Sviluppiamo strumenti che rendono l'imaging piu chiaro e rapido. Uniamo machine learning, collaborazione clinica e design accurato per aiutare i team a pianificare con fiducia, comunicare meglio e risparmiare tempo in contesti critici.",
        paragraph2:
          "Il nostro lavoro si concentra sulla chirurgia addomino-toracica, fornendo un supporto solido per guidare la pianificazione pre-operatoria.",
        list: [
          "Segmentazione AI e visualizzazione 3D",
          "Interoperabilita DICOM/NRRD",
          "Accesso web da qualsiasi piattaforma",
          "Anonimizzazione delle informazioni sul paziente e rispetto della privacy",
        ],
      },
      why: {
        title: "Perche IntusAI",
        cards: [
          { title: "Focus clinico", body: "Progettato con i chirurghi per la pianificazione e la guida pre-operatoria." },
          { title: "Time to value", body: "Inferenza rapida, interfaccia chiara." },
          { title: "Interoperabilita", body: "Formati standard e integrazioni paziente-specifico." },
        ],
        cta: "Esplora VirtualClone (ViC)",
      },
      contact: {
        badge: "Contattaci",
        title: "Vuoi vedere ViC in azione?",
        description:
          "Il nostro team puo guidarti nell'onboarding, nelle integrazioni o in workflow personalizzati. Contattaci dalla pagina di supporto dedicata.",
        cta: "Vai al supporto",
      },
    },
    supportPage: {
      nav: {
        company: "Azienda",
        product: "Prodotto",
        dataset: "Dataset",
        support: "Supporto",
        emailSupport: "Scrivi al supporto",
      },
      hero: {
        badge: "Supporto",
        title: "Siamo qui per aiutare il tuo team con ViC.",
        intro:
          'Scegli una delle opzioni oppure scrivi a <a href="mailto:info@intusai.com">info@intusai.com</a> per un supporto dedicato.',
      },
      cards: {
        manual: {
          title: "Richiedi il manuale utente",
          body: "Ricevi l'ultima versione del manuale di VirtualClone (ViC).",
          cta: "Richiedi il manuale",
        },
        contact: {
          title: "Contattaci",
          body:
            "Hai bisogno di aiuto per onboarding, integrazioni o validazioni cliniche? I nostri ingegneri e specialisti clinici possono seguirti end-to-end.",
          cta: "Parla con noi",
        },
      },
      manualForm: {
        badge: "Richiesta manuale",
        title: "Ricevi l'ultima versione del manuale ViC",
        description: "Compila il form e ti invieremo il manuale aggiornato entro due giorni lavorativi.",
        fields: {
          firstName: "Nome",
          lastName: "Cognome",
          hospital: "Ospedale / Istituto",
          department: "Reparto / Ruolo",
          email: "Email professionale",
          phone: "Telefono (opzionale)",
          country: "Paese",
          useCase: "Use case principale",
          notes: "Note aggiuntive",
        },
        placeholders: {
          firstName: "Maria",
          lastName: "Rossi",
          hospital: "IRCCS San Raffaele",
          department: "Chirurgia epatobiliare",
          email: "nome@ospedale.it",
          phone: "+39 02 1234567",
          country: "Italia",
          useCase: "Pianificazione trapianto di fegato",
          notes: "Descrivi scenario clinico, tempistiche o richieste caso-specifiche.",
        },
        consentPrimary:
          "Confermo di aver letto l'<a href=\"/privacy\">informativa privacy</a> e accetto di essere contattato da IntusAI riguardo a ViC.",
        consentSecondary: "Desidero ricevere aggiornamenti sul prodotto.",
        submit: "Invia richiesta",
        emailHint: "Preferisci la mail? Scrivi a <a href=\"mailto:info@intusai.com\">info@intusai.com</a>.",
      },
      contactSection: {
        badge: "Contattaci",
        title: "Parla direttamente con IntusAI",
        intro: "Rispondiamo entro due giorni lavorativi. Raccontaci come possiamo supportare il tuo workflow o le tue richieste.",
        hqTitle: "Sede",
        hqCity: "Milano, Italia",
        hqAddress: "Via San Senatore 6/1\n20122 Milano (MI)",
        phoneTitle: "Linea diretta",
        phoneValue: "0000 000000",
        phoneHours: "Lun-Ven, 09:00-18:00 CET",
        emailTitle: "Email",
        emailValue: "info@intusai.com",
        form: {
          badge: "Scrivici",
          title: "Parlaci di cosa hai bisogno",
          name: "Nome e cognome",
          email: "Email professionale",
          message: "Messaggio",
          placeholderName: "Dr.ssa Elisa Conti",
          placeholderEmail: "elisa.conti@ospedale.it",
          placeholderMessage: "Descrivi scenario clinico, tempistiche o richieste specifiche.",
          privacy:
            "Accetto l'<a href=\"/privacy\">informativa privacy</a> e di essere contattato per la mia richiesta.",
          submit: "Invia messaggio",
        },
      },
    },
  },
};

export type Locale = keyof typeof translations;
export type TranslationDict = typeof translations.en;
